name: bluej
version: "4.2.2"
summary: A free Java Development Environment designed for beginners, used by millions
description: |
  BlueJ is a free IDE for writing Java programs designed for beginners.
  It graphically shows the class structure of an applications, suitable for educational purposes.
  For further visualization, the source code is highlighted.

base: core18
confinement: strict

apps:
  bluej:
    extensions:
      - gnome-3-28
    command: bluej-launch
    #desktop: usr/share/applications/bluej.desktop
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind

parts:
  bluej:
    plugin: ant
    source: https://bluej.org/download/files/source/BlueJ-source-422.zip
    source-type: zip
    build-packages:
      - openjdk-11-jdk
      - openjfx
      - unzip
    stage-packages: [openjdk-11-jdk, openjfx]
    override-build: |
      cat <<EOF > build.properties
      build_java_home=/usr
      java_command_dir_name=bin
      openjfx_path=/usr/share/openjfx
      run_java_home=${build_java_home}
      EOF
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/bluej
      cp -r lib/* $SNAPCRAFT_PART_INSTALL/usr/share/bluej
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/bluej-launch # Based on the BlueJ startscript (/usr/bin/bluej)
      #!/bin/sh
      CP="\$SNAP/usr/share/bluej/bluej.jar"
      JFXRTOPT=""
      JFXRTOPT2=""
      JAVAFXPATH="\$SNAP/usr/share/java"
      JAVAFXJARS="\$JAVAFXPATH/javafx-base-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-controls-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-fxml-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-graphics-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-media-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-properties-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-swing-11.jar"
      JAVAFXJARS="\$JAVAFXJARS:\$JAVAFXPATH/javafx-web-11.jar"
      CP="\$CP:\$JAVAFXJARS"
      JFXRTOPT="-javafxpath=\$JAVAFXPATH"
      JFXRTOPT2="-javafxjars=\$JAVAFXJARS"
      java -Duser.home=\$SNAP_USER_COMMON -Djavafx.embed.singleThread=true -Dawt.useSystemAAFontSettings=on -Xmx512M -cp "\$CP" bluej.Boot \$JFXRTOPT \$JFXRTOPT2 "\$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bluej-launch
