name: bluej
version: "5.4.1"
summary: A free Java Development Environment designed for beginners, used by millions
description: |
  BlueJ is a free IDE for writing Java programs designed for beginners.
  It graphically shows the class structure of an applications, suitable for educational purposes.
  For further visualization, the source code is highlighted.
base: core22
confinement: strict
architectures: [amd64]

apps:
  bluej:
    extensions:
      - gnome
    command: usr/bin/bluej
    common-id: org.bluej.BlueJ
    plugs:
      - home
      - network
      - network-bind

parts:
  bluej:
    plugin: dump
    source: https://www.bluej.org/download/files/BlueJ-linux-x64-541.deb
    source-type: deb
    override-build: |
      cp -r usr $SNAPCRAFT_PART_INSTALL 
      sed -i 's/\/usr/$SNAP\/usr/g' $SNAPCRAFT_PART_INSTALL/usr/bin/bluej
      sed -i "s/\"\$JAVAPATH.*/\"\$JAVAPATH\/bin\/java\" -Dawt.useSystemAAFontSettings=on -Duser.home=\$SNAP_USER_COMMON -Xmx512M -cp \"\$CP\" bluej.Boot \"\$@\"/" $SNAPCRAFT_PART_INSTALL/usr/bin/bluej
    override-prime: |
      snapcraftctl prime
